version: 2.1

jobs:
  extension:
    parameters:
      image:
        type: string
        default: postgres:9.6
        description: Docker image:tag for Postgres DB
    docker:
      - image: jbergknoff/postgresql-client
      - image: << parameters.image >>
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Super5ecret
          POSTGRES_DB: exploration

    steps:
      - checkout
      - run:
          name: add password file for Postgres
          command: |
            cp .pgpass ${HOME}/.pgpass    
      - run:
          name: migrate DB schema
          command: |
            psql -U admin -d exploration -h 127.0.0.1 -p 5432 -f schema.sql

workflows:
  main:
    jobs:
      - extension:
          name: cimg-postgres
          image: 'cimg/postgres:9.6'
      - extension:
          name: official-postgres
          image: 'postgres:9.6'
